import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import ContextState from "@/context/ContextState";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Explicitly defining weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${inter.variable} ${poppins.variable}`}>
        <ContextState>{children}</ContextState>
      </body>
    </html>
  );
}
